### ISSUE TITLE
Cloud and CoreData : Sharing data between apps.

### ISSUE THREAD

**Issue by Selendri** [hyouuu/iCloudCoreData-Swift#2]
Hi hyouuu,
Thx for your sharing which is very hepful.

With iCloud and CoreData, I've tried to share data between two apps that doesn't work.
Have you any idea to how proceed ? 

Regards,

**Comment by hyouuu** [comment]
Hi Selendri, you mean 2 different apps? They may need to enable iCloud app
group in capabilities, but I'm not certain. Also rarely my app has data not
syncing back issue reported, so be aware about apple's iCloud core data
mechanism

**Comment by hyouuu** [comment]
I'll close this unless you have further questions :)

**Comment by Selendri** [comment]
Sorry for not replying sooner. Yes, I meant  two different apps. I managed using App groups which share the same sqlite file. Thank you very much for your sharing and your answer :)
